steps:
  - name: 'node:10:15.1'
    entrypoint: npm
    args: ['install']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    timeout: '1600s'

substitutions:
  _DISCORD_TOKEN: 'test'

options:
  substitution_option: 'ALLOW_LOOSE'
