steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c','echo "DISCORD_TOKEN=${_DISCORD_TOKEN}" > .env && cat .env']
    timeout: '60s'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy']
    timeout: '600s'

substitutions:
  _DISCORD_TOKEN: 'test'

options:
  substitution_option: 'ALLOW_LOOSE'
