[tool.coverage.run]
include = ["roll_witch/*"]
omit = ["tests/*"]

[tool.coverage.html]
directory = "out/report/coverage_html"

[tool.coverage.xml]
output = "out/report/coverage.xml"

[tool.pytest.ini_options]
pythonpath = "."
